# Generated by Django 5.2.17 on 2026-09-15 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(help_text='Overview of company, domain, and culture')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=150)),
                ('industry', models.CharField(help_text='e.g. Information Technology, FinTech, Consulting', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('package', models.DecimalField(decimal_places=2, help_text='CTC Package in Lakhs Per Annum (LPA), e.g. 8.50', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('eligibility_cgpa', models.DecimalField(decimal_places=2, help_text='Minimum CGPA required to apply', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('eligible_department', models.CharField(default='All', help_text="Comma-separated departments or 'All' (e.g. 'CSE,IT,ECE' or 'All')", max_length=120)),
                ('drive_date', models.DateField(help_text='Date when recruitment drive begins')),
                ('application_deadline', models.DateField(help_text='Last date for students to submit applications')),
                ('vacancies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placement.company')),
            ],
            options={
                'ordering': ['-drive_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Officer or reviewer comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.placementdrive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Selected', max_length=20)),
                ('package', models.DecimalField(decimal_places=2, help_text='Final Offered CTC in LPA', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('joining_date', models.DateField(blank=True, help_text='Expected date of joining', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Placement cell or HR comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='placement.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(help_text='College registration or roll number', max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('AIDS', 'Artificial Intelligence & Data Science')], max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year / Final Year')], default=4)),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative GPA between 0.00 and 10.00', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('skills', models.TextField(blank=True, help_text='Comma-separated or listed skills, e.g. Python, React, SQL')),
                ('resume', models.CharField(blank=True, help_text='Resume link or document URL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_number'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.student'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'placement_drive')},
        ),
    ]
